---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: beyond-the-fringe-tls
spec:
  commonName: beyondthefringeoc.com
  secretName: beyond-the-fringe-tls
  dnsNames:
    - beyondthefringeoc.com
    - hairbyjanine.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
